// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto3DS.Controllers;

#nullable disable

namespace Projeto3DS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240514175633_Cupcake")]
    partial class Cupcake
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Projeto3DS.Models.Categoria", b =>
                {
                    b.Property<int>("categoria_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Categoria_nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("categoria_id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Projeto3DS.Models.Cupcake", b =>
                {
                    b.Property<int>("cupcake_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("categoria_id")
                        .HasColumnType("int");

                    b.Property<string>("cupcake_preferido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("desc_curta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("desc_detalhe")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("em_estoque")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("img_miniatura")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("img_url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<decimal>("preco")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("cupcake_id");

                    b.ToTable("Cupcake");
                });
#pragma warning restore 612, 618
        }
    }
}
